### ISSUE TITLE
Playlist is not working

### ISSUE THREAD

**Issue by ashwamegh** [sabbiriptv/JIO_IPTV#8]
Hi @sabbiriptv ,

Your playlist is not working.

Can you tell me what causes this and if I can help you with this?

**Comment by sabbiriptv** [comment]
The thing is,
i have scripts for Zee5 And JIO but the problem is I don't have paid hosting and as a student i can't afford them too. That's why i am just sharing 3rd party links which gets expire in no time. If I get my hands on paid hosting one day then this repo will be completly changed with EXCLUSIVE content.

If you think you can help me in this regard then it will be great

**Comment by sabbiriptv** [comment]
Hello @ashwamegh The thing is,

i have scripts for Zee5 And JIO but the problem is I don't have paid hosting and as a student i can't afford them too. That's why i am just sharing 3rd party links which gets expire in no time. If I get my hands on paid hosting one day then this repo will be completly changed with EXCLUSIVE content.

If you think you can help me in this regard then it will be great

**Comment by ashwamegh** [comment]
@sabbiriptv Can you share the server code/files which have to be hosted to get Jio/Zee5 running? I will see if I can keep the server up.

**Comment by sabbiriptv** [comment]
@ashwamegh Thanks A Lot Brother!
Can You Give Me Your Telegram or Discord?

**Comment by ashwamegh** [comment]
@ashwamegh Yeah, My discord handle is `ashwamegh#2851`
